name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
    - uses: actions/checkout@v2

    - name: Raku version
      run: raku -v

    - name: install the ssl library
      run: apt-get update && apt-get install -y libssl-dev

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
